### PR TITLE
Fix initial authentication flow

### LINKED ISSUE #40: Async not correctly implemented
Line 71 in miele_at_home.py keeps throwing issues.
This is a follow-up on https://github.com/HomeAssistant-Mods/home-assistant-miele/issues/31

I get this when calling a `miele` service (eg. starting washer from HA):
```[2737078224] I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/miele/miele_at_home.py, line 71: result = await self._session._session.put(```

Also see https://developers.home-assistant.io/docs/asyncio_working_with_async/

### PR DESCRIPTION
**Pull request by bwegman**
This PR fixes the async issue with the login authentication flow. Fixes #40 #39 #36 and #35.

### CODE REVIEW

**Comment by kloknibor** [comment]
Could you do this PR to the dev branch? I was also looking into this but your solutions with functools seems way more simple if it works, so thanks for this! When you did a PR to dev I will test it and if it works forward it asap to master.

**Comment by kloknibor** [comment]
Found out I can change the branch myself, sorry :-)

**Comment by kloknibor** [comment]
PR merged in main branch, thanks for the submission!

**Comment by bwegman** [comment]
You're welcome! Happy to help. Have been using the integration for some time now, works great!

**Pull request merged**
