### PR TITLE
Add programs service

### PR DESCRIPTION
**Pull request by bertvansteen**

### CODE REVIEW

**Comment by bertvansteen** [comment]
accept

**Comment by bertvansteen** [comment]
Sorry, I made this PR by accident while trying to make my own fork visible in HA for testing. My dishwasher does not start with the actions service but can be started via the programs endpoint. I could create a PR (starting from the dev branch?) when the integration is working and there is interest from the community.

**Comment by florie1706** [comment]
I tried it, but I did not get it to run with my dishwasher. Any hints?

**Comment by bertvansteen** [comment]
This automation turns on my and starts my Miele G 7362 SC Vi AutoDos dishwasher.
The state of "remote start sensor control" (next to the on/of button) should be ON. 

It takes about a minute before it actually starts, I have not tried it with removing or reducing the delay., 
 
```yaml
alias: Miele - Start ECO
description: ""
trigger: []
condition: []
action:
  - service: miele.action
    data:
      entity_id: miele.dishwasher
      body:
        powerOn: 1
    alias: Turn on dishwasher
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: miele.program
    data:
      entity_id: miele.dishwasher
      body:
        programId: 3
    alias: Start Miele ECO program
mode: single
```

**Pull request closed without merging**
